"""The phrasebooks: what a controller says, in each language they say it in.

Four languages beyond English and French, chosen because they are the ones
genuinely worked on frequency alongside English in states this system has a
voice for: Spanish across Spain and Latin America, German in Germany, Austria
and German-speaking Switzerland, Italian in Italy, Portuguese in Portugal and
Brazil.

Sources are each state's own phraseology rather than a translation of the
English: AENA's Fraseología Aeronáutica, DFS's Sprechfunkverfahren, ENAV's
Fraseologia Aeronautica, and NAV Portugal / DECEA's Fraseologia. Where a
loanword is what is actually said on the radio -- "squawk" in Germany, "roger"
nowhere -- the loanword is what is written here, because the point is what a
pilot hears.

The Netherlands, Scandinavia and Poland are deliberately absent. They work
English on frequency in practice, which is what this system already does there.
"""

from __future__ import annotations

from .phrasebook import Phrasebook

# --------------------------------------------------------------------------
# Spanish
# --------------------------------------------------------------------------

SPANISH = Phrasebook(
    language="es",
    name="Spanish",
    unit_feet="pies",
    unit_knots="nudos",
    unit_miles="millas",
    unit_mile="milla",
    unit_degrees="grados",
    unit_minutes="minutos",
    unit_minute="minuto",
    flight_level="nivel de vuelo",
    sea_level="a nivel del mar",
    runway_suffix={"L": "izquierda", "R": "derecha", "C": "central",
                   "G": "hierba", "W": "agua"},
    left="izquierda",
    bearings={"north": "norte", "northeast": "noreste", "east": "este",
              "southeast": "sureste", "south": "sur", "southwest": "suroeste",
              "west": "oeste", "northwest": "noroeste"},
    agreeing_forms=(("uno", "una"),),
    miles_take_agreement=True,
    right="derecha",
    legs={"downwind": "viento en cola", "base": "base", "final": "final",
          "crosswind": "viento cruzado", "upwind": "ascenso inicial"},
    airspaces={"B": "la zona terminal", "C": "la zona terminal",
               "D": "la zona de control"},
    vfr_squawk="7000",
    transition_altitude=6000,
    farewells=("Buenos días.", "Buen vuelo.", "Hasta luego."),
    say={
        "wind": "viento", "gusting": "con rachas de",
        "wind_variable": "viento variable", "wind_calm": "viento en calma",
        # clearance delivery
        "cleared_to": "autorizado a {destination} {via}",
        "via_procedure": "por la salida {procedure}",
        "via_transition": ", transición {transition}",
        "via_then": ", después {route}",
        "via_route": "por {route}",
        "climb_initially": "ascienda inicialmente a {altitude}",
        "expect_after": "espere {altitude} {minutes} minutos después del despegue",
        "departure_frequency": "frecuencia de salida {frequency}",
        "squawk": "transpondedor {code}",
        "vfr_leave_airspace": "autorizado a abandonar {airspace}",
        "vfr_direction_approved": "salida {direction} aprobada",
        "vfr_approved": "salida VFR aprobada",
        "maintain_vfr_at_or_below": "mantenga VFR a o por debajo de {altitude}",
        "readback_correct": "colación correcta",
        "negative": "negativo",
        "contact_when": "contacte {station} {frequency} {when}",
        "contact_station_when": "contacte {station} {when}",
        "when_ready_to_taxi": "cuando esté listo para rodar",
        # ground
        "taxi_via": "ruede por {route}",
        "taxi_to_the_runway": "ruede hacia la pista",
        "holding_point": "punto de espera pista {runway}",
        "hold_short": "manténgase antes de la pista {runway}",
        "taxi_to_parking_via": "ruede a {destination} por {route}",
        "taxi_to_parking": "ruede a {destination}",
        "cross_runway": "cruce la pista {runway}",
        "hold_position": "mantenga posición",
        "continue_via": "continúe por {route}",
        "continue_taxi": "continúe el rodaje",
        "give_way": "ceda el paso a {traffic}",
        "then_continue": "después continúe",
        "pushback_approved": "retroceso y puesta en marcha aprobados",
        "report_ready_to_taxi": "notifique listo para rodar",
        # tower
        "runway_is": "pista {runway}",
        "line_up_and_wait": "alinéese y espere",
        "cleared_takeoff": "autorizado a despegar",
        "cleared_to_land": "autorizado a aterrizar",
        "cleared_option": "autorizada la opción",
        "go_around": "motor y al aire",
        "continue_approach": "continúe la aproximación",
        "number": "número {number}",
        "follow": "siga a {traffic}",
        "enter_pattern": "incorpórese al circuito por la {direction} pista {runway}",
        "report": "notifique {what}",
        "extend_downwind": "prolongue viento en cola",
        "i_will_call_your_base": "le aviso para base",
        "cleared_low_approach": "autorizada pasada baja",
        # radar
        "radar_contact": "identificado por radar",
        "radar_contact_lost": "contacto radar perdido",
        "climb_to": "ascienda a {altitude}",
        "descend_to": "descienda a {altitude}",
        "descend_discretion": "descienda a discreción a {altitude}",
        "maintain_altitude": "mantenga {altitude}",
        "cross_at": "cruce {fix} a {altitude}",
        "at_or_above": "a o por encima de",
        "at_or_below": "a o por debajo de",
        "turn_heading": "gire a la {side} rumbo {heading}",
        "fly_heading": "rumbo {heading}",
        "direct_to": "directo a {fix}",
        "resume_own_navigation": "reanude navegación propia",
        "maintain_speed": "mantenga {speed}",
        "reduce_speed": "reduzca a {speed}",
        "or_greater": "o más",
        "or_less": "o menos",
        "resume_normal_speed": "reanude velocidad normal",
        "traffic": "tráfico",
        "oclock": "a las {hour}",
        "at_distance": "a {distance}",
        "altitude_unknown": "nivel desconocido",
        "traffic_no_factor": "el tráfico anterior no es factor",
        "maintain_visual_separation": "mantenga su propia separación visual",
        "follow_that_traffic": "siga a ese tráfico",
        # approach
        "expect_approach": "espere la aproximación {approach} pista {runway}",
        "at_airport": "en {airport}",
        "distance_from": "a {distance} de {fix}",
        "maintain_until_established":
            "mantenga {altitude} hasta establecido en el localizador",
        "cleared_approach": "autorizado aproximación {approach} pista {runway}",
        "cleared_straight_in_approach":
            "autorizado aproximación directa {approach} pista {runway}",
        "cleared_visual": "autorizada aproximación visual pista {runway}",
        "visual_approach_word": "visual",
        "cleared_visual_at": "autorizada aproximación visual {airport} pista {runway}",
        "report_field_in_sight": "notifique campo a la vista",
        "field_at": "{airport} a las {hour}, {distance}",
        "descend_via": "descienda por la {arrival}",
        "climb_via": "ascienda por la {departure}",
        "except_maintain": "excepto mantenga {altitude}",
        "hold_at": "espere al {direction} de {fix}",
        "on_radial": "en el radial {radial}",
        "turns_to": "virajes por la {side}",
        "legs_of": "tramos de {minutes} {unit}",
        "expect_further_clearance": "autorización posterior prevista a las {time}",
        # handoffs
        "contact": "contacte {station} {frequency}",
        "monitor": "escuche {station} {frequency}",
        "remain_this_frequency": "permanezca en esta frecuencia",
        "welcome_to": "bienvenido a {place}",
        "frequency_change_approved": "cambio de frecuencia aprobado",
        "radar_service_terminated": "servicio radar terminado",
        "ifr_cancellation_received": "cancelación IFR recibida",
        # general
        "ident": "ident",
        "say_again": "repita",
        "say_again_item": "repita su {item}",
        "roger": "recibido",
        "standby": "espere",
        "unable": "imposible",
        "verify": "confirme {item}",
        "read_you": "le recibo {readability} sobre {scale}",
        "how_do_you_hear": "cómo me recibe",
        "read_back": "colacione",
        "maintain_present_altitude": "mantenga su nivel actual",
        "say_again_the_fix": "repita el punto",
        "say_your_destination": "notifique su destino",
        # the aircraft and the request do not agree
        "you_are_airborne": "está en vuelo",
        "you_are_on_the_ground": "está en tierra",
        "say_intentions": "notifique intenciones",
        "already_cleared_takeoff": "ya está autorizado a despegar",
        "already_cleared_to_land": "ya está autorizado a aterrizar",
        # unprompted
        "hold_position_now": "mantenga posición",
        "entered_runway_without_clearance":
            "ha entrado en la pista {runway} sin autorización",
        "departed_without_clearance": "ha despegado de la pista {runway} sin autorización",
        "departed_without_clearance_no_runway": "ha despegado sin autorización",
        "landed_without_clearance": "ha aterrizado en la pista {runway} sin autorización",
        "landed_without_clearance_no_runway": "ha aterrizado sin autorización",
        "report_will_be_filed": "se emitirá un informe de incidente",
        "call_after_flight": "llame a {station} después del vuelo",
        "call_after_parking": "llame a {station} después de estacionar",
        # emergencies
        "state_nature_of_emergency": "notifique la naturaleza de la emergencia",
        "souls_and_fuel": "personas a bordo y combustible remanente",
        "you_have_priority": "tiene prioridad",
        "expect_runway": "espere pista {runway}",
        "equipment_standing_by": "los servicios de emergencia están preparados",
        "the_airport_is_yours": "el aeropuerto es suyo",
        "expecting": "espero {calls}",
        "or_else": "o",
        # insisting on a readback
        "read_back_all": "colacione el mensaje completo",
        "read_back_item": "colacione {item}",
        "read_back_hold_short":
            "colacione las instrucciones de punto de espera",
        "i_say_again": "repito",
        "item_hold_short": "las instrucciones de punto de espera",
        "item_runway": "la pista",
        "item_altitude": "el nivel",
        "item_heading": "el rumbo",
        "item_squawk": "el código de transpondedor",
        "item_frequency": "la frecuencia",
        "item_speed": "la velocidad",
        # VFR: the circuit, the airspace, the levels
        "enter_leg": "incorpórese en {leg} por la {direction} pista {runway}",
        "straight_in": "aproximación directa pista {runway}",
        "closed_traffic_approved": "circuito por la {direction} aprobado",
        "make_short_approach": "haga aproximación corta",
        "turn_out_approved": "viraje a la {direction} aprobado",
        "on_course_approved": "continúe en ruta aprobado",
        "maintain_vfr": "mantenga VFR",
        "maintain_vfr_at_or_above": "mantenga VFR a o por encima de {altitude}",
        "altitude_your_discretion": "altitud a su discreción",
        "cleared_through": "autorizado a cruzar {airspace}",
        "remain_clear_of": "permanezca fuera de {airspace}",
        "clear_of": "fuera de {airspace}",
        "miles_final": "en final a {distance}",
        "flight_following_unavailable":
            "imposible el servicio de información por carga de trabajo",
        "midfield_downwind": "en mitad del viento en cola",
        "turning_base": "virando a base",
        "entering_downwind": "entrando en viento en cola",
        # fragments passed back in
        "route_radar_vectors": "vectores radar, después ruta prevista",
        "runway_heading": "rumbo de pista",
        "parking": "la plataforma",
        "unknown_destination": "su destino",
        "default_approach": "ILS",
    },
)


# --------------------------------------------------------------------------
# German
# --------------------------------------------------------------------------

GERMAN = Phrasebook(
    language="de",
    name="German",
    unit_feet="Fuß",
    unit_knots="Knoten",
    unit_miles="Meilen",
    unit_mile="Meile",
    unit_degrees="Grad",
    unit_minutes="Minuten",
    unit_minute="Minute",
    flight_level="Flugfläche",
    sea_level="auf Meereshöhe",
    runway_suffix={"L": "links", "R": "rechts", "C": "Mitte",
                   "G": "Gras", "W": "Wasser"},
    left="links",
    bearings={"north": "Norden", "northeast": "Nordosten",
              "east": "Osten", "southeast": "Südosten", "south": "Süden",
              "southwest": "Südwesten", "west": "Westen",
              "northwest": "Nordwesten"},
    agreeing_forms=(("eins", "eine"),),
    miles_take_agreement=True,
    right="rechts",
    legs={"downwind": "Gegenanflug", "base": "Queranflug",
          "final": "Endanflug", "crosswind": "Querabflug",
          "upwind": "Gegenanflug entgegen"},
    airspaces={"B": "Nahverkehrszone", "C": "Nahverkehrszone",
               "D": "Kontrollzone"},
    vfr_squawk="7000",
    transition_altitude=5000,
    farewells=("Guten Tag.", "Guten Flug.", "Auf Wiederhören."),
    say={
        "wind": "Wind", "gusting": "in Böen",
        # Not verified against DFS phraseology.
        "wind_variable": "Wind umlaufend", "wind_calm": "Wind still",
        # clearance delivery
        "cleared_to": "Freigabe nach {destination} {via}",
        "via_procedure": "über den Abflug {procedure}",
        "via_transition": ", Übergang {transition}",
        "via_then": ", danach {route}",
        "via_route": "über {route}",
        "climb_initially": "steigen Sie zunächst auf {altitude}",
        "expect_after": "erwarten Sie {altitude} {minutes} Minuten nach dem Start",
        "departure_frequency": "Abflugfrequenz {frequency}",
        "squawk": "Squawk {code}",
        "vfr_leave_airspace": "Freigabe zum Verlassen der {airspace}",
        "vfr_direction_approved": "Abflug nach {direction} genehmigt",
        "vfr_approved": "VFR-Abflug genehmigt",
        "maintain_vfr_at_or_below": "bleiben Sie VFR auf oder unter {altitude}",
        "readback_correct": "Rückmeldung richtig",
        "negative": "negativ",
        "contact_when": "rufen Sie {station} {frequency} {when}",
        "contact_station_when": "rufen Sie {station} {when}",
        "when_ready_to_taxi": "wenn rollbereit",
        # ground
        "taxi_via": "rollen Sie über {route}",
        "taxi_to_the_runway": "rollen Sie zur Piste",
        "holding_point": "zum Rollhalt Piste {runway}",
        "hold_short": "halten Sie kurz vor Piste {runway}",
        "taxi_to_parking_via": "rollen Sie zu {destination} über {route}",
        "taxi_to_parking": "rollen Sie zu {destination}",
        "cross_runway": "überqueren Sie Piste {runway}",
        "hold_position": "halten Sie Position",
        "continue_via": "rollen Sie weiter über {route}",
        "continue_taxi": "rollen Sie weiter",
        "give_way": "geben Sie {traffic} Vorrang",
        "then_continue": "danach weiter",
        "pushback_approved": "Push-back und Anlassen genehmigt",
        "report_ready_to_taxi": "melden Sie rollbereit",
        # tower
        "runway_is": "Piste {runway}",
        "line_up_and_wait": "reihen Sie sich ein und warten",
        "cleared_takeoff": "Start frei",
        "cleared_to_land": "Landung frei",
        "cleared_option": "Option genehmigt",
        "go_around": "durchstarten",
        "continue_approach": "setzen Sie den Anflug fort",
        "number": "Nummer {number}",
        "follow": "folgen Sie {traffic}",
        "enter_pattern": "fliegen Sie Platzrunde {direction} Piste {runway}",
        "report": "melden Sie {what}",
        "extend_downwind": "verlängern Sie den Gegenanflug",
        "i_will_call_your_base": "ich rufe Sie für den Queranflug",
        "cleared_low_approach": "Tiefanflug genehmigt",
        # radar
        "radar_contact": "Radarkontakt",
        "radar_contact_lost": "Radarkontakt verloren",
        "climb_to": "steigen Sie auf {altitude}",
        "descend_to": "sinken Sie auf {altitude}",
        "descend_discretion": "sinken Sie nach eigenem Ermessen auf {altitude}",
        "maintain_altitude": "halten Sie {altitude}",
        "cross_at": "überfliegen Sie {fix} in {altitude}",
        "at_or_above": "auf oder über",
        "at_or_below": "auf oder unter",
        "turn_heading": "drehen Sie {side} auf Kurs {heading}",
        "fly_heading": "fliegen Sie Kurs {heading}",
        "direct_to": "direkt {fix}",
        "resume_own_navigation": "nehmen Sie die Eigennavigation wieder auf",
        "maintain_speed": "halten Sie {speed}",
        "reduce_speed": "reduzieren Sie auf {speed}",
        "or_greater": "oder mehr",
        "or_less": "oder weniger",
        "resume_normal_speed": "nehmen Sie normale Geschwindigkeit wieder auf",
        "traffic": "Verkehr",
        "oclock": "auf {hour} Uhr",
        "at_distance": "in {distance}",
        "altitude_unknown": "Höhe unbekannt",
        "traffic_no_factor": "der vorherige Verkehr ist kein Faktor",
        "maintain_visual_separation": "halten Sie eigene Sichtstaffelung",
        "follow_that_traffic": "folgen Sie diesem Verkehr",
        # approach
        "expect_approach": "erwarten Sie den {approach} Anflug Piste {runway}",
        "at_airport": "in {airport}",
        "distance_from": "in {distance} von {fix}",
        "maintain_until_established":
            "halten Sie {altitude} bis zum Einflug in den Localizer",
        "cleared_approach": "Freigabe zum {approach} Anflug Piste {runway}",
        "cleared_straight_in_approach":
            "Freigabe zum direkten {approach} Anflug Piste {runway}",
        "cleared_visual": "Freigabe zum Sichtanflug Piste {runway}",
        # Read into "den {approach} Anflug"; not verified against DFS.
        "visual_approach_word": "Sicht",
        "cleared_visual_at": "Freigabe zum Sichtanflug {airport} Piste {runway}",
        "report_field_in_sight": "melden Sie den Platz in Sicht",
        "field_at": "{airport} auf {hour} Uhr, {distance}",
        "descend_via": "sinken Sie gemäß {arrival}",
        "climb_via": "steigen Sie gemäß {departure}",
        "except_maintain": "außer halten Sie {altitude}",
        "hold_at": "halten Sie {direction} von {fix}",
        "on_radial": "auf dem Radial {radial}",
        "turns_to": "Kurven nach {side}",
        "legs_of": "Schenkel von {minutes} {unit}",
        "expect_further_clearance": "weitere Freigabe erwartet um {time}",
        # handoffs
        "contact": "rufen Sie {station} {frequency}",
        "monitor": "hören Sie {station} {frequency}",
        "remain_this_frequency": "bleiben Sie auf dieser Frequenz",
        "welcome_to": "willkommen in {place}",
        "frequency_change_approved": "Frequenzwechsel genehmigt",
        "radar_service_terminated": "Radardienst beendet",
        "ifr_cancellation_received": "IFR-Annullierung erhalten",
        # general
        "ident": "Ident",
        "say_again": "wiederholen Sie",
        "say_again_item": "wiederholen Sie {item}",
        "roger": "verstanden",
        "standby": "warten Sie",
        "unable": "nicht möglich",
        "verify": "bestätigen Sie {item}",
        "read_you": "ich höre Sie {readability} von {scale}",
        "how_do_you_hear": "wie hören Sie mich",
        "read_back": "wiederholen Sie",
        "maintain_present_altitude": "halten Sie Ihre gegenwärtige Höhe",
        "say_again_the_fix": "wiederholen Sie den Punkt",
        "say_your_destination": "melden Sie Ihr Ziel",
        # the aircraft and the request do not agree
        "you_are_airborne": "Sie sind in der Luft",
        "you_are_on_the_ground": "Sie sind am Boden",
        "say_intentions": "melden Sie Ihre Absichten",
        "already_cleared_takeoff": "Sie haben bereits Startfreigabe",
        "already_cleared_to_land": "Sie haben bereits Landefreigabe",
        # unprompted
        "hold_position_now": "halten Sie Position",
        "entered_runway_without_clearance":
            "Sie sind ohne Freigabe auf Piste {runway} gerollt",
        "departed_without_clearance": "Sie sind ohne Startfreigabe von Piste {runway} gestartet",
        "departed_without_clearance_no_runway": "Sie sind ohne Startfreigabe gestartet",
        "landed_without_clearance": "Sie sind ohne Landefreigabe auf Piste {runway} gelandet",
        "landed_without_clearance_no_runway": "Sie sind ohne Landefreigabe gelandet",
        "report_will_be_filed": "eine Meldung wird weitergegeben",
        "call_after_flight": "rufen Sie {station} nach dem Flug an",
        "call_after_parking": "rufen Sie {station} nach dem Abstellen an",
        # emergencies
        "state_nature_of_emergency": "melden Sie die Art des Notfalls",
        "souls_and_fuel": "Personen an Bord und verbleibender Kraftstoff",
        "you_have_priority": "Sie haben Vorrang",
        "expect_runway": "erwarten Sie Piste {runway}",
        "equipment_standing_by": "die Rettungsdienste stehen bereit",
        "the_airport_is_yours": "der Flughafen gehört Ihnen",
        "expecting": "erwarte {calls}",
        "or_else": "oder",
        # insisting on a readback
        "read_back_all": "wiederholen Sie die vollständige Freigabe",
        "read_back_item": "wiederholen Sie {item}",
        "read_back_hold_short": "wiederholen Sie die Rollhalt-Anweisung",
        "i_say_again": "ich wiederhole",
        "item_hold_short": "die Rollhalt-Anweisung",
        "item_runway": "die Piste",
        "item_altitude": "die Flughöhe",
        "item_heading": "den Kurs",
        "item_squawk": "den Transpondercode",
        "item_frequency": "die Frequenz",
        "item_speed": "die Geschwindigkeit",
        # VFR: the circuit, the airspace, the levels
        "enter_leg": "fliegen Sie in den {leg} ein, Platzrunde {direction}, "
                     "Piste {runway}",
        "straight_in": "direkter Anflug Piste {runway}",
        "closed_traffic_approved": "Platzrunde {direction} genehmigt",
        "make_short_approach": "fliegen Sie einen kurzen Anflug",
        "turn_out_approved": "Ausflug nach {direction} genehmigt",
        "on_course_approved": "Weiterflug auf Kurs genehmigt",
        "maintain_vfr": "bleiben Sie VFR",
        "maintain_vfr_at_or_above": "bleiben Sie VFR auf oder über {altitude}",
        "altitude_your_discretion": "Flughöhe nach eigenem Ermessen",
        "cleared_through": "Durchflug durch die {airspace} genehmigt",
        "remain_clear_of": "bleiben Sie außerhalb der {airspace}",
        "clear_of": "außerhalb der {airspace}",
        "miles_final": "Endanflug in {distance}",
        "flight_following_unavailable":
            "Fluginformationsdienst nicht möglich, Arbeitsbelastung",
        "midfield_downwind": "Mitte Gegenanflug",
        "turning_base": "Queranflug",
        "entering_downwind": "Einflug Gegenanflug",
        # fragments passed back in
        "route_radar_vectors": "Radarführung, danach wie geplant",
        "runway_heading": "Pistenkurs",
        "parking": "das Vorfeld",
        "unknown_destination": "Ihr Ziel",
        "default_approach": "ILS",
    },
)


# --------------------------------------------------------------------------
# Italian
# --------------------------------------------------------------------------

ITALIAN = Phrasebook(
    language="it",
    name="Italian",
    unit_feet="piedi",
    unit_knots="nodi",
    unit_miles="miglia",
    unit_mile="miglio",
    unit_degrees="gradi",
    unit_minutes="minuti",
    unit_minute="minuto",
    flight_level="livello di volo",
    sea_level="al livello del mare",
    runway_suffix={"L": "sinistra", "R": "destra", "C": "centrale",
                   "G": "erba", "W": "acqua"},
    left="sinistra",
    bearings={"north": "nord", "northeast": "nord-est", "east": "est",
              "southeast": "sud-est", "south": "sud", "southwest": "sud-ovest",
              "west": "ovest", "northwest": "nord-ovest"},
    agreeing_forms=(("uno", "un"),),
    miles_take_agreement=True,
    right="destra",
    legs={"downwind": "sottovento", "base": "base", "final": "finale",
          "crosswind": "traverso", "upwind": "sopravento"},
    airspaces={"B": "zona terminale", "C": "zona terminale",
               "D": "zona di controllo"},
    vfr_squawk="7000",
    transition_altitude=6000,
    farewells=("Buongiorno.", "Buon volo.", "Arrivederci."),
    say={
        "wind": "vento", "gusting": "con raffiche di",
        "wind_variable": "vento variabile", "wind_calm": "vento calmo",
        # clearance delivery
        "cleared_to": "autorizzato a {destination} {via}",
        "via_procedure": "via la partenza {procedure}",
        "via_transition": ", transizione {transition}",
        "via_then": ", poi {route}",
        "via_route": "via {route}",
        "climb_initially": "salga inizialmente a {altitude}",
        "expect_after": "preveda {altitude} {minutes} minuti dopo il decollo",
        "departure_frequency": "frequenza di partenza {frequency}",
        "squawk": "transponder {code}",
        "vfr_leave_airspace": "autorizzato a lasciare la {airspace}",
        "vfr_direction_approved": "partenza {direction} approvata",
        "vfr_approved": "partenza VFR approvata",
        "maintain_vfr_at_or_below": "mantenga VFR a o al di sotto di {altitude}",
        "readback_correct": "riporto corretto",
        "negative": "negativo",
        "contact_when": "contatti {station} {frequency} {when}",
        "contact_station_when": "contatti {station} {when}",
        "when_ready_to_taxi": "quando pronto al rullaggio",
        # ground
        "taxi_via": "rulli via {route}",
        "taxi_to_the_runway": "rulli verso la pista",
        "holding_point": "punto attesa pista {runway}",
        "hold_short": "mantenga prima della pista {runway}",
        "taxi_to_parking_via": "rulli al {destination} via {route}",
        "taxi_to_parking": "rulli al {destination}",
        "cross_runway": "attraversi la pista {runway}",
        "hold_position": "mantenga la posizione",
        "continue_via": "prosegua via {route}",
        "continue_taxi": "prosegua il rullaggio",
        "give_way": "dia la precedenza a {traffic}",
        "then_continue": "poi prosegua",
        "pushback_approved": "push-back e messa in moto approvati",
        "report_ready_to_taxi": "riporti pronto al rullaggio",
        # tower
        "runway_is": "pista {runway}",
        "line_up_and_wait": "si allinei e attenda",
        "cleared_takeoff": "autorizzato al decollo",
        "cleared_to_land": "autorizzato all'atterraggio",
        "cleared_option": "autorizzato all'opzione",
        "go_around": "riattacchi",
        "continue_approach": "prosegua l'avvicinamento",
        "number": "numero {number}",
        "follow": "segua {traffic}",
        "enter_pattern": "si inserisca nel circuito a {direction} pista {runway}",
        "report": "riporti {what}",
        "extend_downwind": "prolunghi il sottovento",
        "i_will_call_your_base": "la richiamo per il base",
        "cleared_low_approach": "autorizzato passaggio basso",
        # radar
        "radar_contact": "contatto radar",
        "radar_contact_lost": "contatto radar perso",
        "climb_to": "salga a {altitude}",
        "descend_to": "scenda a {altitude}",
        "descend_discretion": "scenda a sua discrezione a {altitude}",
        "maintain_altitude": "mantenga {altitude}",
        "cross_at": "attraversi {fix} a {altitude}",
        "at_or_above": "a o al di sopra di",
        "at_or_below": "a o al di sotto di",
        "turn_heading": "viri a {side} prua {heading}",
        "fly_heading": "prua {heading}",
        "direct_to": "diretto {fix}",
        "resume_own_navigation": "riprenda la navigazione autonoma",
        "maintain_speed": "mantenga {speed}",
        "reduce_speed": "riduca a {speed}",
        "or_greater": "o più",
        "or_less": "o meno",
        "resume_normal_speed": "riprenda velocità normale",
        "traffic": "traffico",
        "oclock": "a ore {hour}",
        "at_distance": "a {distance}",
        "altitude_unknown": "livello sconosciuto",
        "traffic_no_factor": "il traffico precedente non è un fattore",
        "maintain_visual_separation": "mantenga la propria separazione a vista",
        "follow_that_traffic": "segua quel traffico",
        # approach
        "expect_approach": "preveda l'avvicinamento {approach} pista {runway}",
        "at_airport": "a {airport}",
        "distance_from": "a {distance} da {fix}",
        "maintain_until_established":
            "mantenga {altitude} fino a stabilizzato sul localizzatore",
        "cleared_approach": "autorizzato avvicinamento {approach} pista {runway}",
        "cleared_straight_in_approach":
            "autorizzato avvicinamento diretto {approach} pista {runway}",
        "cleared_visual": "autorizzato avvicinamento a vista pista {runway}",
        "visual_approach_word": "a vista",
        "cleared_visual_at": "autorizzato avvicinamento a vista {airport} pista {runway}",
        "report_field_in_sight": "riporti campo in vista",
        "field_at": "{airport} a ore {hour}, {distance}",
        "descend_via": "scenda secondo la {arrival}",
        "climb_via": "salga secondo la {departure}",
        "except_maintain": "eccetto mantenga {altitude}",
        "hold_at": "attenda a {direction} di {fix}",
        "on_radial": "sul radiale {radial}",
        "turns_to": "virate a {side}",
        "legs_of": "tratte di {minutes} {unit}",
        "expect_further_clearance": "ulteriore autorizzazione prevista alle {time}",
        # handoffs
        "contact": "contatti {station} {frequency}",
        "monitor": "ascolti {station} {frequency}",
        "remain_this_frequency": "rimanga su questa frequenza",
        "welcome_to": "benvenuti a {place}",
        "frequency_change_approved": "cambio frequenza approvato",
        "radar_service_terminated": "servizio radar terminato",
        "ifr_cancellation_received": "cancellazione IFR ricevuta",
        # general
        "ident": "ident",
        "say_again": "ripeta",
        "say_again_item": "ripeta {item}",
        "roger": "ricevuto",
        "standby": "attenda",
        "unable": "impossibile",
        "verify": "confermi {item}",
        "read_you": "la ricevo {readability} su {scale}",
        "how_do_you_hear": "come mi riceve",
        "read_back": "riporti",
        "maintain_present_altitude": "mantenga il livello attuale",
        "say_again_the_fix": "ripeta il punto",
        "say_your_destination": "riporti la sua destinazione",
        # the aircraft and the request do not agree
        "you_are_airborne": "è in volo",
        "you_are_on_the_ground": "è al suolo",
        "say_intentions": "riporti le sue intenzioni",
        "already_cleared_takeoff": "è già autorizzato al decollo",
        "already_cleared_to_land": "è già autorizzato all'atterraggio",
        # unprompted
        "hold_position_now": "mantenga la posizione",
        "entered_runway_without_clearance":
            "è entrato in pista {runway} senza autorizzazione",
        "departed_without_clearance": "è decollato dalla pista {runway} senza autorizzazione",
        "departed_without_clearance_no_runway": "è decollato senza autorizzazione",
        "landed_without_clearance": "è atterrato sulla pista {runway} senza autorizzazione",
        "landed_without_clearance_no_runway": "è atterrato senza autorizzazione",
        "report_will_be_filed": "sarà trasmesso un rapporto di inconveniente",
        "call_after_flight": "chiami {station} dopo il volo",
        "call_after_parking": "chiami {station} dopo il parcheggio",
        # emergencies
        "state_nature_of_emergency": "riporti la natura dell'emergenza",
        "souls_and_fuel": "persone a bordo e carburante rimanente",
        "you_have_priority": "ha la priorità",
        "expect_runway": "preveda pista {runway}",
        "equipment_standing_by": "i mezzi di soccorso sono pronti",
        "the_airport_is_yours": "l'aeroporto è suo",
        "expecting": "attendo {calls}",
        "or_else": "o",
        # insisting on a readback
        "read_back_all": "riporti l'intero messaggio",
        "read_back_item": "riporti {item}",
        "read_back_hold_short":
            "riporti le istruzioni di attesa prima della pista",
        "i_say_again": "ripeto",
        "item_hold_short": "le istruzioni di attesa prima della pista",
        "item_runway": "la pista",
        "item_altitude": "la quota",
        "item_heading": "la prua",
        "item_squawk": "il codice transponder",
        "item_frequency": "la frequenza",
        "item_speed": "la velocità",
        # VFR: the circuit, the airspace, the levels
        "enter_leg": "si inserisca in {leg}, circuito a {direction}, pista {runway}",
        "straight_in": "avvicinamento diretto pista {runway}",
        "closed_traffic_approved": "circuito a {direction} approvato",
        "make_short_approach": "esegua un avvicinamento corto",
        "turn_out_approved": "virata a {direction} approvata",
        "on_course_approved": "prosecuzione in rotta approvata",
        "maintain_vfr": "mantenga VFR",
        "maintain_vfr_at_or_above": "mantenga VFR a o al di sopra di {altitude}",
        "altitude_your_discretion": "quota a sua discrezione",
        "cleared_through": "autorizzato ad attraversare la {airspace}",
        "remain_clear_of": "rimanga fuori dalla {airspace}",
        "clear_of": "fuori dalla {airspace}",
        "miles_final": "in finale a {distance}",
        "flight_following_unavailable":
            "servizio informazioni non disponibile per carico di lavoro",
        "midfield_downwind": "metà sottovento",
        "turning_base": "in virata per la base",
        "entering_downwind": "in ingresso sottovento",
        # fragments passed back in
        "route_radar_vectors": "guida radar, poi come da piano",
        "runway_heading": "prua pista",
        "parking": "il piazzale",
        "unknown_destination": "la sua destinazione",
        "default_approach": "ILS",
    },
)


# --------------------------------------------------------------------------
# Portuguese
# --------------------------------------------------------------------------

PORTUGUESE = Phrasebook(
    language="pt",
    name="Portuguese",
    unit_feet="pés",
    unit_knots="nós",
    unit_miles="milhas",
    unit_mile="milha",
    unit_degrees="graus",
    unit_minutes="minutos",
    unit_minute="minuto",
    flight_level="nível de voo",
    sea_level="ao nível do mar",
    runway_suffix={"L": "esquerda", "R": "direita", "C": "central",
                   "G": "relva", "W": "água"},
    left="esquerda",
    bearings={"north": "norte", "northeast": "nordeste", "east": "este",
              "southeast": "sudeste", "south": "sul", "southwest": "sudoeste",
              "west": "oeste", "northwest": "noroeste"},
    agreeing_forms=(("dois", "duas"), ("um", "uma")),
    miles_take_agreement=True,
    right="direita",
    legs={"downwind": "perna do vento", "base": "perna base",
          "final": "final", "crosswind": "perna do través",
          "upwind": "subida inicial"},
    airspaces={"B": "área terminal", "C": "área terminal",
               "D": "zona de controlo"},
    vfr_squawk="7000",
    transition_altitude=6000,
    farewells=("Bom dia.", "Bom voo.", "Até logo."),
    say={
        "wind": "vento", "gusting": "com rajadas de",
        "wind_variable": "vento variável", "wind_calm": "vento calmo",
        # clearance delivery
        "cleared_to": "autorizado para {destination} {via}",
        "via_procedure": "pela saída {procedure}",
        "via_transition": ", transição {transition}",
        "via_then": ", depois {route}",
        "via_route": "por {route}",
        "climb_initially": "suba inicialmente para {altitude}",
        "expect_after": "espere {altitude} {minutes} minutos após a descolagem",
        "departure_frequency": "frequência de partida {frequency}",
        "squawk": "transponder {code}",
        "vfr_leave_airspace": "autorizado a deixar a {airspace}",
        "vfr_direction_approved": "saída {direction} aprovada",
        "vfr_approved": "saída VFR aprovada",
        "maintain_vfr_at_or_below": "mantenha VFR a ou abaixo de {altitude}",
        "readback_correct": "colação correta",
        "negative": "negativo",
        "contact_when": "contacte {station} {frequency} {when}",
        "contact_station_when": "contacte {station} {when}",
        "when_ready_to_taxi": "quando pronto para taxiar",
        # ground
        "taxi_via": "taxie por {route}",
        "taxi_to_the_runway": "taxie para a pista",
        "holding_point": "ponto de espera pista {runway}",
        "hold_short": "mantenha antes da pista {runway}",
        "taxi_to_parking_via": "taxie para {destination} por {route}",
        "taxi_to_parking": "taxie para {destination}",
        "cross_runway": "atravesse a pista {runway}",
        "hold_position": "mantenha posição",
        "continue_via": "continue por {route}",
        "continue_taxi": "continue a taxiar",
        "give_way": "ceda passagem a {traffic}",
        "then_continue": "depois continue",
        "pushback_approved": "push-back e arranque aprovados",
        "report_ready_to_taxi": "reporte pronto para taxiar",
        # tower
        "runway_is": "pista {runway}",
        "line_up_and_wait": "alinhe e aguarde",
        "cleared_takeoff": "autorizado a descolar",
        "cleared_to_land": "autorizado a aterrar",
        "cleared_option": "autorizada a opção",
        "go_around": "arremeta",
        "continue_approach": "continue a aproximação",
        "number": "número {number}",
        "follow": "siga {traffic}",
        "enter_pattern": "entre no circuito pela {direction} pista {runway}",
        "report": "reporte {what}",
        "extend_downwind": "prolongue a perna do vento",
        "i_will_call_your_base": "chamo-o para a base",
        "cleared_low_approach": "autorizada passagem baixa",
        # radar
        "radar_contact": "contacto radar",
        "radar_contact_lost": "contacto radar perdido",
        "climb_to": "suba para {altitude}",
        "descend_to": "desça para {altitude}",
        "descend_discretion": "desça ao seu critério para {altitude}",
        "maintain_altitude": "mantenha {altitude}",
        "cross_at": "cruze {fix} a {altitude}",
        "at_or_above": "a ou acima de",
        "at_or_below": "a ou abaixo de",
        "turn_heading": "vire à {side} proa {heading}",
        "fly_heading": "proa {heading}",
        "direct_to": "directo {fix}",
        "resume_own_navigation": "retome a navegação própria",
        "maintain_speed": "mantenha {speed}",
        "reduce_speed": "reduza para {speed}",
        "or_greater": "ou mais",
        "or_less": "ou menos",
        "resume_normal_speed": "retome velocidade normal",
        "traffic": "tráfego",
        "oclock": "às {hour} horas",
        "at_distance": "a {distance}",
        "altitude_unknown": "nível desconhecido",
        "traffic_no_factor": "o tráfego anterior não é factor",
        "maintain_visual_separation": "mantenha a sua própria separação visual",
        "follow_that_traffic": "siga esse tráfego",
        # approach
        "expect_approach": "espere a aproximação {approach} pista {runway}",
        "at_airport": "em {airport}",
        "distance_from": "a {distance} de {fix}",
        "maintain_until_established":
            "mantenha {altitude} até estabelecido no localizador",
        "cleared_approach": "autorizado aproximação {approach} pista {runway}",
        "cleared_straight_in_approach":
            "autorizado aproximação directa {approach} pista {runway}",
        "cleared_visual": "autorizada aproximação visual pista {runway}",
        "visual_approach_word": "visual",
        "cleared_visual_at": "autorizada aproximação visual {airport} pista {runway}",
        "report_field_in_sight": "reporte campo à vista",
        "field_at": "{airport} às {hour} horas, {distance}",
        "descend_via": "desça pela {arrival}",
        "climb_via": "suba pela {departure}",
        "except_maintain": "excepto mantenha {altitude}",
        "hold_at": "espere a {direction} de {fix}",
        "on_radial": "no radial {radial}",
        "turns_to": "curvas à {side}",
        "legs_of": "pernas de {minutes} {unit}",
        "expect_further_clearance": "autorização posterior prevista às {time}",
        # handoffs
        "contact": "contacte {station} {frequency}",
        "monitor": "escute {station} {frequency}",
        "remain_this_frequency": "permaneça nesta frequência",
        "welcome_to": "bem-vindo a {place}",
        "frequency_change_approved": "mudança de frequência aprovada",
        "radar_service_terminated": "serviço radar terminado",
        "ifr_cancellation_received": "cancelamento IFR recebido",
        # general
        "ident": "ident",
        "say_again": "repita",
        "say_again_item": "repita {item}",
        "roger": "recebido",
        "standby": "aguarde",
        "unable": "impossível",
        "verify": "confirme {item}",
        "read_you": "recebo-o {readability} sobre {scale}",
        "how_do_you_hear": "como me recebe",
        "read_back": "colacione",
        "maintain_present_altitude": "mantenha o seu nível actual",
        "say_again_the_fix": "repita o ponto",
        "say_your_destination": "reporte o seu destino",
        # the aircraft and the request do not agree
        "you_are_airborne": "está em voo",
        "you_are_on_the_ground": "está no solo",
        "say_intentions": "reporte as suas intenções",
        "already_cleared_takeoff": "já está autorizado a descolar",
        "already_cleared_to_land": "já está autorizado a aterrar",
        # unprompted
        "hold_position_now": "mantenha posição",
        "entered_runway_without_clearance":
            "entrou na pista {runway} sem autorização",
        "departed_without_clearance": "descolou da pista {runway} sem autorização",
        "departed_without_clearance_no_runway": "descolou sem autorização",
        "landed_without_clearance": "aterrou na pista {runway} sem autorização",
        "landed_without_clearance_no_runway": "aterrou sem autorização",
        "report_will_be_filed": "será transmitido um relatório de incidente",
        "call_after_flight": "contacte {station} após o voo",
        "call_after_parking": "contacte {station} após estacionar",
        # emergencies
        "state_nature_of_emergency": "reporte a natureza da emergência",
        "souls_and_fuel": "pessoas a bordo e combustível remanescente",
        "you_have_priority": "tem prioridade",
        "expect_runway": "espere pista {runway}",
        "equipment_standing_by": "os meios de socorro estão prontos",
        "the_airport_is_yours": "o aeroporto é seu",
        "expecting": "aguardo {calls}",
        "or_else": "ou",
        # insisting on a readback
        "read_back_all": "colacione a mensagem completa",
        "read_back_item": "colacione {item}",
        "read_back_hold_short":
            "colacione as instruções de ponto de espera",
        "i_say_again": "repito",
        "item_hold_short": "as instruções de ponto de espera",
        "item_runway": "a pista",
        "item_altitude": "a altitude",
        "item_heading": "a proa",
        "item_squawk": "o código transponder",
        "item_frequency": "a frequência",
        "item_speed": "a velocidade",
        # VFR: the circuit, the airspace, the levels
        "enter_leg": "entre na {leg} pela {direction}, pista {runway}",
        "straight_in": "aproximação directa pista {runway}",
        "closed_traffic_approved": "circuito pela {direction} aprovado",
        "make_short_approach": "faça uma aproximação curta",
        "turn_out_approved": "curva à {direction} aprovada",
        "on_course_approved": "prossiga em rota aprovado",
        "maintain_vfr": "mantenha VFR",
        "maintain_vfr_at_or_above": "mantenha VFR a ou acima de {altitude}",
        "altitude_your_discretion": "altitude ao seu critério",
        "cleared_through": "autorizado a atravessar a {airspace}",
        "remain_clear_of": "permaneça fora da {airspace}",
        "clear_of": "fora da {airspace}",
        "miles_final": "em final a {distance}",
        "flight_following_unavailable":
            "serviço de informação indisponível por carga de trabalho",
        "midfield_downwind": "a meio da perna do vento",
        "turning_base": "a curvar para a base",
        "entering_downwind": "a entrar na perna do vento",
        # fragments passed back in
        "route_radar_vectors": "vectores radar, depois como planeado",
        "runway_heading": "proa da pista",
        "parking": "a placa",
        "unknown_destination": "o seu destino",
        "default_approach": "ILS",
    },
)


BOOKS: dict[str, Phrasebook] = {
    "es": SPANISH,
    "de": GERMAN,
    "it": ITALIAN,
    "pt": PORTUGUESE,
}


__all__ = ["BOOKS", "SPANISH", "GERMAN", "ITALIAN", "PORTUGUESE"]
