"""Controller phraseology.

Every word a controller says in this system is produced here, from a fixed
template. Nothing is generated by a language model. That is a deliberate
architectural choice: a model asked to "sound like ATC" will drift, invent
instructions that do not exist, and phrase the same clearance differently every
time. Templates cannot. The cost is that only the instructions written here can
ever be issued; the benefit is that every instruction issued is correct, and a
pilot who reads back what they heard is reading back real phraseology.

Sources followed:

  * FAA JO 7110.65   -- Air Traffic Control (US phraseology, ``faa`` dialect)
  * FAA AIM ch. 4-2  -- Radio communications phraseology and technique
  * ICAO Doc 4444    -- PANS-ATM ch. 12, radiotelephony phraseology
  * ICAO Doc 9432    -- Manual of Radiotelephony

Where the two dialects differ the template branches: the FAA says "climb and
maintain one two thousand" and "altimeter two niner niner two", ICAO says
"climb to flight level one two zero" and "QNH one zero one three".

Controlled variety comes from :func:`_pick`, which chooses between phrasings
that are *all* correct, keyed on a stable hash so the same situation always
produces the same words.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from typing import Sequence

from . import speech as sp

Dialect = sp.Dialect


def _pick(options: Sequence[str], key: str) -> str:
    """Deterministically choose one of several equally correct phrasings."""
    if len(options) == 1:
        return options[0]
    h = int.from_bytes(hashlib.sha256(key.encode("utf-8")).digest()[:4], "big")
    return options[h % len(options)]


def language_of(phraseology) -> str:
    """Which language a phraseology speaks.

    The dialect and the language are not the same question -- English at Orly
    is ICAO English, not US English -- so a phraseology states its language
    outright rather than having it inferred from the dialect. Everything that
    addresses an aircraft has to ask, because a callsign is spoken differently
    in each language.
    """
    return getattr(phraseology, "language", "") or "en"


def _join(*parts: str) -> str:
    """Join clause fragments, dropping empties and tidying punctuation."""
    text = ", ".join(p.strip().strip(",") for p in parts if p and p.strip().strip(","))
    return text.replace(" ,", ",").replace(",,", ",").strip(" ,")


def _sentence(text: str) -> str:
    """One full stop at the end, however many the parts arrived with."""
    text = (text or "").rstrip()
    return text if text.endswith((".", "!", "?")) else text + "."


def without_callsign(text: str, aircraft) -> str:
    """An instruction with the callsign it opens with taken off the front.

    Every instruction a controller gives begins by naming the aeroplane, which
    is right, and which makes repeating one awkward: the repeat has to name
    the aeroplane too, and then the instruction names it again.

        November two sierra papa, I say again. November two sierra papa,
        contact de Gaulle Ground one two one decimal six one zero.

    Nobody says that. The callsign is said once, the announcement follows it,
    and then the instruction carries on from where the announcement left off.
    Which form the instruction used -- the full callsign or the abbreviated
    one, in whichever language it was said in -- is not knowable from here, so
    every form the aeroplane answers to is tried, longest first.
    """
    body = (text or "").lstrip()
    if aircraft is None or not body:
        return body

    forms = {aircraft.spoken(False), aircraft.spoken(True)}
    for callsign in [aircraft.callsign, *aircraft.callsigns.values()]:
        for form in (callsign.spoken_full, callsign.spoken_short):
            if not form:
                continue
            forms.add(form)
            if aircraft.wake:
                forms.add(f"{form} {aircraft.wake}")
    for form in sorted((f for f in forms if f), key=len, reverse=True):
        if body.lower().startswith(form.lower()):
            return body[len(form):].lstrip().lstrip(",").lstrip()
    return body


# --------------------------------------------------------------------------
# wake turbulence
# --------------------------------------------------------------------------

# ICAO wake categories that are spoken as part of the callsign. A 747 is
# "heavy" on every transmission; an A380 is "super". Getting this wrong is
# immediately obvious to an airline pilot.
SUPER_TYPES = {"A388", "A124", "A225"}
HEAVY_TYPES = {
    "A332", "A333", "A337", "A338", "A339", "A342", "A343", "A345", "A346",
    "A359", "A35K", "A3ST", "B742", "B743", "B744", "B748", "B74S", "B762",
    "B763", "B764", "B772", "B773", "B77L", "B77W", "B778", "B779", "B788",
    "B789", "B78X", "MD11", "DC10", "IL96", "A306", "A310", "C5M", "C17",
    "K35R", "B52", "AN22", "IL76",
}


def wake_suffix(aircraft_type: str) -> str:
    """``"heavy"``, ``"super"`` or empty, appended to the spoken callsign."""
    code = (aircraft_type or "").strip().upper()
    if code in SUPER_TYPES:
        return "super"
    if code in HEAVY_TYPES:
        return "heavy"
    return ""


def fix_name(ident: str, spoken: str = "") -> str:
    """How a waypoint or navaid is said on the radio.

    Five-letter RNAV fixes are deliberately coined to be pronounceable and are
    spoken as words -- CAMRN is "cam-run", never "Charlie Alpha Mike Romeo
    November". Two- and three-letter navaid identifiers are spelled out when
    all we have is the identifier; pass ``spoken`` with the navaid's published
    name ("Robbinsville") whenever it is known, because that is what a
    controller actually says.
    """
    ident = (ident or "").strip().upper()
    if spoken:
        return spoken
    if not ident:
        return ""
    if len(ident) <= 3 or not ident.isalpha():
        return sp.letters(ident)
    # Title case gives the synthesiser its best chance at a natural reading
    # rather than spelling the letters out.
    return ident.capitalize()


# --------------------------------------------------------------------------
# context
# --------------------------------------------------------------------------


@dataclass
class Aircraft:
    """What the controller knows about the aircraft it is talking to.

    A callsign is spoken differently in different languages: ``AFR1234`` is
    "Airfrans twelve thirty four" to an English-speaking controller and "Air
    France mille deux cent trente-quatre" to a French one. Both forms are held
    here, and ``language`` selects between them, so the phraseology templates
    can stay ignorant of the question.
    """

    callsign: sp.Callsign
    type_code: str = ""
    wake: str = ""                 # "", "heavy", "super"
    is_heavy: bool = False
    # Alternative spoken forms, keyed by language code.
    callsigns: dict[str, sp.Callsign] = field(default_factory=dict)
    language: str = "en"

    def for_language(self, language: str) -> sp.Callsign:
        return self.callsigns.get((language or "en")[:2], self.callsign)

    def spoken(self, abbreviated: bool = False) -> str:
        base = self.for_language(self.language).spoken(abbreviated)
        return f"{base} {self.wake}".strip() if self.wake else base

    def variants(self) -> list[str]:
        """Every spoken and written form, for matching what the pilot said."""
        found = {self.callsign.written}
        for callsign in [self.callsign, *self.callsigns.values()]:
            found.add(callsign.spoken_full)
            found.add(callsign.spoken_short)
        return [v for v in found if v]


@dataclass
class Weather:
    wind_dir: float = 0.0
    wind_kt: float = 0.0
    gust_kt: float = 0.0
    visibility_sm: float = 10.0
    altimeter_inhg: float = 29.92
    qnh_hpa: float = 1013.0
    temperature_c: float = 15.0
    dewpoint_c: float = 10.0
    clouds: list[tuple[str, int]] = field(default_factory=list)  # [("FEW", 4500)]
    remarks: str = ""
    raw: str = ""
    # Magnetic variation at the field, east positive. ``wind_dir`` stays true,
    # as observed and as the runway headings in the data are; a spoken wind
    # subtracts this (see :func:`spoken_wind_direction`).
    variation: float = 0.0
    # A METAR "VRB": no direction at all, which is not a wind from the north.
    variable: bool = False
    # Where the wind and pressure were read from, for the decision log:
    # "metar KBOS", "nearest KLGA", "sim+metar KBOS", "sim", "default".
    source: str = ""


def spoken_wind_direction(weather: Weather) -> float | str:
    """The direction a controller reads out: magnetic, in tens, or "VRB".

    Observations are true and every wind a controller or an ATIS speaks is
    magnetic (ICAO Doc 4444 6.6; FAA JO 7110.65 2-6-4), rounded to ten
    degrees as both read it. A field with no variation known reads the
    observation as it is.
    """
    if weather.variable:
        return "VRB"
    magnetic = (float(weather.wind_dir) - float(weather.variation or 0.0)) % 360.0
    tens = int(round(magnetic / 10.0)) * 10 % 360
    return float(tens or 360) if weather.wind_kt >= 0.5 else 0.0


class Phraseology:
    """Builds controller transmissions for one dialect."""

    # The dialect varies; the language does not. This is the English class.
    language = "en"

    def __init__(self, dialect: Dialect = "faa", strict_icao_digits: bool = False,
                 transition: int = 18000):
        """``dialect`` selects the phrasing; ``strict_icao_digits`` the numbers.

        ICAO Annex 10 prescribes "tree", "fower" and "fife" alongside "niner",
        and UK CAP 413 repeats them. In practice only "niner" is universal,
        with "fife" fairly common and "tree"/"fower" rare outside training.
        Reading every number the strict way sounds theatrical to a line pilot,
        so the default keeps ICAO *phrasing* (decimal, QNH, "climb to") with
        ordinary digit words. Set this flag for the by-the-book reading.

        ``transition`` is where altitudes become flight levels in this
        region. It belongs to the object rather than to each call because
        forgetting it is silent and wrong in the same direction every time:
        every caller that left it out got eighteen thousand feet, which is
        correct in the Americas and nowhere else, so an aircraft over London
        reported "one eight thousand" for a level everyone on the frequency
        calls flight level one eight zero. A caller with a better answer --
        the controller, who knows which airport the instruction is for --
        still passes one.
        """
        self.dialect = dialect
        self.strict_icao_digits = strict_icao_digits
        self.transition = int(transition) or 18000
        # Only the digit table differs; everything else follows ``dialect``.
        self.digit_dialect: Dialect = (
            "icao" if (dialect == "icao" and strict_icao_digits) else "faa"
        )

    # ------------------------------------------------------------------
    # primitives
    # ------------------------------------------------------------------

    def d(self, value) -> str:
        return sp.digits(value, self.digit_dialect)

    def alt(self, feet: float, transition: int = 0, level_from: int = 0) -> str:
        return sp.altitude(feet, self.digit_dialect,
                           transition or self.transition, level_from)

    def freq(self, mhz: float) -> str:
        # The separator word follows the region; the digits follow the style.
        text = sp.frequency(mhz, self.digit_dialect)
        if self.dialect == "icao":
            text = text.replace(" point ", " decimal ")
        return text

    def hdg(self, degrees: float) -> str:
        return sp.heading(degrees, self.digit_dialect)

    def rwy(self, ident: str) -> str:
        # The leading zero is regional; the digit words are a style choice.
        return sp.runway(ident, self.dialect, self.digit_dialect)

    def addressed(self, aircraft: Aircraft, station: str = "",
                  abbreviated: bool = False) -> str:
        """Open a transmission: aircraft first, then who is calling."""
        who = aircraft.spoken(abbreviated)
        return _join(who, station) if station else who

    # ------------------------------------------------------------------
    # clearance delivery
    # ------------------------------------------------------------------

    def ifr_clearance(
        self,
        aircraft: Aircraft,
        station: str,
        destination: str,
        *,
        departure_procedure: str = "",
        transition: str = "",
        route: str = "as filed",
        initial_altitude: float = 5000,
        cruise_altitude: float = 0,
        expect_minutes: int = 10,
        departure_freq: float = 0.0,
        squawk: str = "1200",
        transition_altitude: int = 0,
    ) -> str:
        """A full IFR clearance in CRAFT order.

        Clearance limit, Route, Altitude, Frequency, Transponder -- the order
        every instrument pilot is taught to write it down in, and the order
        controllers actually read it.
        """
        # --- clearance limit and route ---
        if departure_procedure:
            via = f"via the {departure_procedure} departure"
            if transition:
                via += f", {transition} transition"
            via += f", then {route}"
        else:
            via = f"via {route}"

        cleared_to = f"cleared to the {destination} airport {via}"
        if self.dialect == "icao":
            cleared_to = f"cleared to {destination} {via}"

        # --- altitude ---
        if self.dialect == "faa":
            climb = f"maintain {self.alt(initial_altitude, transition_altitude)}"
            if cruise_altitude and cruise_altitude > initial_altitude:
                climb += (
                    f", expect {self.alt(cruise_altitude, transition_altitude)} "
                    f"{self.d(expect_minutes)} minutes after departure"
                )
        else:
            climb = f"climb to {self.alt(initial_altitude, transition_altitude)}"
            if cruise_altitude and cruise_altitude > initial_altitude:
                climb += (
                    f", expect {self.alt(cruise_altitude, transition_altitude)} "
                    f"{self.d(expect_minutes)} minutes after departure"
                )

        parts = [self.addressed(aircraft, station), cleared_to, climb]

        if departure_freq:
            label = "departure frequency" if self.dialect == "faa" else "departure frequency"
            parts.append(f"{label} {self.freq(departure_freq)}")
        parts.append(f"squawk {sp.squawk(squawk, self.digit_dialect)}")
        return _join(*parts) + "."

    def vfr_departure_clearance(
        self,
        aircraft: Aircraft,
        station: str,
        *,
        airspace: str = "",
        departure_freq: float = 0.0,
        squawk: str = "1200",
        altitude_restriction: float = 0.0,
        direction: str = "",
    ) -> str:
        """VFR release out of controlled airspace.

        A VFR flight is not cleared anywhere. It is released in a direction,
        held at or below a level where something is above it, given a code and
        sent on its way -- so this says "departure approved" and "maintain
        VFR", never "cleared to" and never a level to maintain.
        """
        parts = [self.addressed(aircraft, station)]
        if airspace:
            body = f"cleared out of the {airspace}"
            if direction:
                body += f", {direction} departure approved"
            parts.append(body)
        elif direction:
            parts.append(f"{direction} departure approved")
        else:
            parts.append("VFR departure approved")
        if altitude_restriction:
            parts.append(f"maintain VFR at or below {self.alt(altitude_restriction)}")
        else:
            parts.append("maintain VFR")
        if departure_freq:
            parts.append(f"departure frequency {self.freq(departure_freq)}")
        parts.append(f"squawk {sp.squawk(squawk, self.digit_dialect)}")
        return _join(*parts) + "."

    def readback_correct(
        self, aircraft: Aircraft, *, next_station: str = "", next_freq: float = 0.0,
        when: str = "when ready to taxi",
    ) -> str:
        parts = [aircraft.spoken(True), "readback correct"]
        if next_station and next_freq:
            parts.append(f"contact {next_station} {self.freq(next_freq)} {when}")
        elif next_station:
            parts.append(f"contact {next_station} {when}")
        return _join(*parts) + "."

    def readback_incorrect(self, aircraft: Aircraft, correction: str) -> str:
        """Correct one item without re-reading the whole clearance."""
        return _join(aircraft.spoken(True), "negative", correction) + "."

    # What a controller says to a pilot who has not read back. FAA JO 7110.65
    # 4-3-2 and 2-4-3 make the readback of a hold-short instruction mandatory
    # and name it explicitly -- "read back hold short instructions" -- which is
    # why the wording changes with what is owed rather than being one phrase.
    READBACK_ITEM_NAMES: dict[str, str] = {
        "hold_short": "hold short instructions",
        "runway": "the runway assignment",
        "altitude_ft": "the altitude",
        "heading": "the heading",
        "squawk": "the transponder code",
        "frequency": "the frequency",
        "speed_kt": "the speed",
    }

    def read_back_instruction(self, aircraft: Aircraft,
                              items: Sequence[str] = ()) -> str:
        """Ask for a readback that was not given.

        Named item by item where the controller would name it. "Read back hold
        short instructions" is the phrase in the book, and it is the one case
        where a controller is required to insist rather than let it go.
        """
        if "hold_short" in items:
            body = "read back hold short instructions"
        elif len(items) == 1:
            body = f"read back {self.READBACK_ITEM_NAMES.get(items[0], 'all instructions')}"
        else:
            body = "read back all instructions"
        return _join(aircraft.spoken(True), body) + "."

    def say_again_instruction(self, aircraft: Aircraft, text: str) -> str:
        """Re-read an instruction in full, for a pilot who plainly missed it.

        The announcement goes between the callsign and the instruction, and
        the instruction's own copy of the callsign comes off -- otherwise the
        aeroplane is named twice in a row, which is what this used to do.
        """
        return _sentence(_join(aircraft.spoken(True), "I say again",
                               without_callsign(text, aircraft)))

    # ------------------------------------------------------------------
    # ground
    # ------------------------------------------------------------------

    def taxi_to_runway(
        self,
        aircraft: Aircraft,
        station: str,
        runway: str,
        route: Sequence[str],
        *,
        hold_short: str = "",
        altimeter: float = 0.0,
        abbreviated: bool = True,
    ) -> str:
        """Taxi instruction.

        FAA JO 7110.65 10-3-1 requires the departure runway to be stated first,
        then the route, and a hold-short instruction for every runway crossed
        that is not explicitly cleared. The runway assignment is not a takeoff
        clearance and never implies one.
        """
        parts = [self.addressed(aircraft, station, abbreviated)]
        parts.append(f"runway {self.rwy(runway)}")
        if route:
            parts.append(f"taxi via {sp.taxi_route(route)}")
        else:
            parts.append("taxi to the runway")
        if hold_short:
            parts.append(f"hold short of runway {self.rwy(hold_short)}")
        if altimeter:
            parts.append(self.pressure(altimeter))
        return _join(*parts) + "."

    def taxi_to_parking(
        self, aircraft: Aircraft, station: str, route: Sequence[str],
        destination: str = "the ramp", *, hold_short: str = "",
        abbreviated: bool = True,
    ) -> str:
        parts = [self.addressed(aircraft, station, abbreviated)]
        if route:
            parts.append(f"taxi to {destination} via {sp.taxi_route(route)}")
        else:
            parts.append(f"taxi to {destination}")
        if hold_short:
            parts.append(f"hold short of runway {self.rwy(hold_short)}")
        return _join(*parts) + "."

    def cross_runway(
        self, aircraft: Aircraft, runway: str, *, then: str = "", abbreviated: bool = True
    ) -> str:
        parts = [aircraft.spoken(abbreviated), f"cross runway {self.rwy(runway)}"]
        if then:
            parts.append(then)
        return _join(*parts) + "."

    def hold_short_instruction(self, aircraft: Aircraft, runway: str) -> str:
        return _join(aircraft.spoken(True),
                     f"hold short of runway {self.rwy(runway)}") + "."

    def hold_position(self, aircraft: Aircraft) -> str:
        word = "hold position" if self.dialect == "faa" else "hold position"
        return _join(aircraft.spoken(True), word) + "."

    def continue_taxi(self, aircraft: Aircraft, route: Sequence[str] = ()) -> str:
        if route:
            return _join(aircraft.spoken(True),
                         f"continue taxi via {sp.taxi_route(route)}") + "."
        return _join(aircraft.spoken(True), "continue taxi") + "."

    def give_way(self, aircraft: Aircraft, traffic: str) -> str:
        return _join(aircraft.spoken(True), f"give way to {traffic}",
                     "then continue taxi") + "."

    # ------------------------------------------------------------------
    # tower
    # ------------------------------------------------------------------

    def line_up_and_wait(
        self, aircraft: Aircraft, runway: str, *, reason: str = "",
        station: str = "", abbreviated: bool = True,
    ) -> str:
        """"Line up and wait" replaced "position and hold" in the US in 2010."""
        parts = [self.addressed(aircraft, station, abbreviated),
                 f"runway {self.rwy(runway)}", "line up and wait"]
        if reason:
            parts.append(reason)
        return _join(*parts) + "."

    def cleared_for_takeoff(
        self,
        aircraft: Aircraft,
        runway: str,
        weather: Weather | None = None,
        *,
        station: str = "",
        after_departure: str = "",
        abbreviated: bool = True,
        traffic: str = "",
    ) -> str:
        parts = [self.addressed(aircraft, station, abbreviated)]
        if traffic:
            parts.append(traffic)
        if weather is not None:
            parts.append(self.wind(weather))
        parts.append(f"runway {self.rwy(runway)}")
        if after_departure:
            parts.append(after_departure)
        parts.append("cleared for takeoff")
        return _join(*parts) + "."

    def cleared_to_land(
        self,
        aircraft: Aircraft,
        runway: str,
        weather: Weather | None = None,
        *,
        station: str = "",
        sequence: str = "",
        abbreviated: bool = True,
    ) -> str:
        parts = [self.addressed(aircraft, station, abbreviated)]
        if sequence:
            parts.append(sequence)
        if weather is not None:
            parts.append(self.wind(weather))
        parts.append(f"runway {self.rwy(runway)}")
        parts.append("cleared to land")
        return _join(*parts) + "."

    def cleared_touch_and_go(self, aircraft: Aircraft, runway: str,
                             weather: Weather | None = None, *,
                             sequence: str = "", station: str = "",
                             abbreviated: bool = True) -> str:
        """"Cleared for the option" leaves the choice to the pilot.

        FAA JO 7110.65 3-10-6: it authorises a touch-and-go, a low approach, a
        missed approach, a stop-and-go or a full stop, and it is what a tower
        issues to an aircraft doing circuits rather than reissuing a landing
        clearance every time round.
        """
        parts = [self.addressed(aircraft, station, abbreviated)]
        if sequence:
            parts.append(sequence)
        if weather is not None:
            parts.append(self.wind(weather))
        parts += [f"runway {self.rwy(runway)}", "cleared for the option"]
        return _join(*parts) + "."

    def closed_traffic_approved(
        self, aircraft: Aircraft, runway: str, direction: str = "left",
        weather: Weather | None = None, *, station: str = "",
        abbreviated: bool = True,
    ) -> str:
        """Takeoff clearance for an aircraft staying in the circuit."""
        parts = [self.addressed(aircraft, station, abbreviated)]
        if weather is not None:
            parts.append(self.wind(weather))
        parts += [f"runway {self.rwy(runway)}", "cleared for takeoff",
                  f"{direction} closed traffic approved"]
        return _join(*parts) + "."

    def make_short_approach(self, aircraft: Aircraft, reason: str = "") -> str:
        parts = [aircraft.spoken(True), "make short approach"]
        if reason:
            parts.append(reason)
        return _join(*parts) + "."

    def turn_out_approved(self, aircraft: Aircraft, direction: str = "") -> str:
        """What a VFR departure is given instead of "fly runway heading"."""
        if direction:
            return _join(aircraft.spoken(True),
                         f"{direction} turn out approved") + "."
        return _join(aircraft.spoken(True), "on course approved") + "."

    def go_around(self, aircraft: Aircraft, reason: str = "",
                  instruction: str = "") -> str:
        parts = [aircraft.spoken(True), "go around"]
        if reason:
            parts.append(reason)
        if instruction:
            parts.append(instruction)
        return _join(*parts) + "."

    def continue_approach(self, aircraft: Aircraft, reason: str = "") -> str:
        parts = [aircraft.spoken(True), "continue approach"]
        if reason:
            parts.append(reason)
        return _join(*parts) + "."

    def sequence_number(self, position: int, traffic: str = "") -> str:
        """``"number two, follow the Boeing seven three seven on short final"``."""
        words = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five",
                 6: "six", 7: "seven", 8: "eight"}
        text = f"number {words.get(position, self.d(position))}"
        if traffic:
            text += f", follow {traffic}"
        return text

    def enter_pattern(
        self, aircraft: Aircraft, station: str, runway: str, leg: str = "downwind",
        direction: str = "left", *, report: str = "", weather: Weather | None = None,
        sequence: str = "", straight_in: bool = False,
    ) -> str:
        """Join instruction for a VFR arrival.

        FAA JO 7110.65 3-10-2: the leg to enter, the runway, and a reporting
        point. "Make left traffic" is the phrase when the aircraft is joining
        the circuit at whichever leg suits it; naming the leg -- "enter left
        downwind" -- is what a tower says when it wants a particular one, and
        is the commoner instruction, so the leg is said unless it is empty.
        """
        parts = [self.addressed(aircraft, station)]
        if sequence:
            parts.append(sequence)
        if straight_in:
            parts.append(f"make straight-in runway {self.rwy(runway)}")
        elif leg:
            parts.append(f"enter {direction} {leg} runway {self.rwy(runway)}")
        else:
            parts.append(f"make {direction} traffic runway {self.rwy(runway)}")
        if report:
            parts.append(f"report {report}")
        if weather is not None:
            parts.append(self.wind(weather))
            parts.append(self.pressure(
                weather.altimeter_inhg if self.dialect == "faa" else weather.qnh_hpa
            ))
        return _join(*parts) + "."

    def report_position(self, aircraft: Aircraft, point: str) -> str:
        """``"report midfield downwind"``, ``"report a two mile final"``.

        The reporting point is what a tower uses instead of radar to sequence
        a circuit, so it is an instruction in its own right rather than a
        clause hanging off another one.
        """
        return _join(aircraft.spoken(True), f"report {point}") + "."

    def extend_downwind(self, aircraft: Aircraft, reason: str = "") -> str:
        parts = [aircraft.spoken(True), "extend downwind"]
        if reason:
            parts.append(reason)
        parts.append("I'll call your base")
        return _join(*parts) + "."

    def cleared_low_approach(self, aircraft: Aircraft, runway: str) -> str:
        return _join(aircraft.spoken(True), f"runway {self.rwy(runway)}",
                     "cleared low approach") + "."

    def wind_check(self, weather: Weather, aircraft: Aircraft | None = None) -> str:
        parts = []
        if aircraft:
            parts.append(aircraft.spoken(True))
        parts.append(self.wind(weather))
        return _join(*parts) + "."

    # ------------------------------------------------------------------
    # radar: departure, approach, centre
    # ------------------------------------------------------------------

    def radar_contact(
        self, aircraft: Aircraft, station: str, *, position: str = "",
        instruction: str = "", abbreviated: bool = False,
    ) -> str:
        """Tell an aircraft it has been identified.

        "Radar contact" is the American phrase and this said it everywhere,
        which is a London controller speaking FAA. ICAO Doc 4444 12.3.1.4 and
        CAP 413 both say "identified", and a British pilot hears the
        difference immediately -- it is one of the handful of phrases that
        marks out which side of the Atlantic a frequency is on.
        """
        found = "radar contact" if self.dialect == "faa" else "identified"
        parts = [self.addressed(aircraft, station, abbreviated), found]
        if position:
            parts.append(position)
        if instruction:
            parts.append(instruction)
        return _join(*parts) + "."

    def radar_contact_lost(self, aircraft: Aircraft, instruction: str = "") -> str:
        lost = ("radar contact lost" if self.dialect == "faa"
                else "identification lost")
        parts = [aircraft.spoken(True), lost]
        if instruction:
            parts.append(instruction)
        return _join(*parts) + "."

    def climb_maintain(self, aircraft: Aircraft, feet: float, *,
                       station: str = "", transition_altitude: int = 0,
                       restriction: str = "", abbreviated: bool = True) -> str:
        level = self.alt(feet, transition_altitude)
        verb = "climb and maintain" if self.dialect == "faa" else "climb to"
        parts = [self.addressed(aircraft, station, abbreviated), f"{verb} {level}"]
        if restriction:
            parts.append(restriction)
        return _join(*parts) + "."

    def descend_maintain(self, aircraft: Aircraft, feet: float, *,
                         station: str = "", transition_altitude: int = 0,
                         restriction: str = "", pilots_discretion: bool = False,
                         abbreviated: bool = True, transition_level: int = 0,
                         pressure: float = 0.0) -> str:
        """A descent, with the pressure setting when it leaves the levels.

        ``transition_level`` makes the boundary the level rather than the
        altitude, which is the rule for a descent through the layer.
        ``pressure`` is said after an altitude and never after a level; the
        caller passes it on the first clearance below the transition level
        (ICAO Doc 9432 "descend to altitude 4000 ft, QNH 1018"; FAA JO
        7110.65 2-7-1 issues the altimeter before leaving the flight levels).
        """
        level = self.alt(feet, transition_altitude, transition_level)
        if pilots_discretion:
            verb = "descend at pilot's discretion, maintain"
        else:
            verb = "descend and maintain" if self.dialect == "faa" else "descend to"
        parts = [self.addressed(aircraft, station, abbreviated), f"{verb} {level}"]
        if pressure and not sp.is_flight_level(
                feet, transition_altitude or self.transition, transition_level):
            parts.append(self.pressure(pressure))
        if restriction:
            parts.append(restriction)
        return _join(*parts) + "."

    def maintain_altitude(self, aircraft: Aircraft, feet: float,
                          transition_altitude: int = 0) -> str:
        return _join(aircraft.spoken(True),
                     f"maintain {self.alt(feet, transition_altitude)}") + "."

    def cross_at(self, fix: str, feet: float, *, at_or_above: bool = False,
                 at_or_below: bool = False, transition_altitude: int = 0,
                 fix_spoken: str = "") -> str:
        qualifier = ""
        if at_or_above:
            qualifier = "at or above "
        elif at_or_below:
            qualifier = "at or below "
        return (f"cross {fix_name(fix, fix_spoken)} at {qualifier}"
                f"{self.alt(feet, transition_altitude)}")

    def turn_heading(self, aircraft: Aircraft, degrees: float, direction: str = "",
                     *, station: str = "", reason: str = "",
                     abbreviated: bool = True) -> str:
        if direction in ("left", "right"):
            body = f"turn {direction} heading {self.hdg(degrees)}"
        else:
            body = f"fly heading {self.hdg(degrees)}"
        parts = [self.addressed(aircraft, station, abbreviated), body]
        if reason:
            parts.append(reason)
        return _join(*parts) + "."

    def direct_to(self, aircraft: Aircraft, fix: str, *, station: str = "",
                  abbreviated: bool = True, fix_spoken: str = "") -> str:
        spoken_fix = fix_name(fix, fix_spoken)
        verb = _pick(("proceed direct", "cleared direct"), fix + aircraft.callsign.written)
        return _join(self.addressed(aircraft, station, abbreviated),
                     f"{verb} {spoken_fix}") + "."

    def resume_own_navigation(self, aircraft: Aircraft) -> str:
        return _join(aircraft.spoken(True), "resume own navigation") + "."

    def speed_restriction(self, aircraft: Aircraft, knots: float, *,
                          maintain: bool = False, or_greater: bool = False,
                          or_less: bool = False) -> str:
        if maintain:
            body = f"maintain {sp.speed(knots, self.digit_dialect)} knots"
        else:
            body = f"reduce speed to {sp.speed(knots, self.digit_dialect)} knots"
        if or_greater:
            body += " or greater"
        elif or_less:
            body += " or less"
        return _join(aircraft.spoken(True), body) + "."

    def resume_normal_speed(self, aircraft: Aircraft) -> str:
        return _join(aircraft.spoken(True), "resume normal speed") + "."

    def traffic_advisory(
        self, aircraft: Aircraft, oclock: int, distance_nm: float,
        direction: str = "", traffic_type: str = "", altitude_ft: float = 0.0,
        *, transition_altitude: int = 0,
    ) -> str:
        """``"traffic, two o'clock, five miles, eastbound, a Boeing 737 at 8,000"``."""
        words = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six",
                 7: "seven", 8: "eight", 9: "niner", 10: "ten", 11: "eleven",
                 12: "twelve"}
        parts = [aircraft.spoken(True), "traffic",
                 f"{words.get(oclock, self.d(oclock))} o'clock",
                 sp.distance(distance_nm, self.digit_dialect)]
        if direction:
            parts.append(direction)
        if traffic_type:
            parts.append(traffic_type)
        if altitude_ft:
            parts.append(f"at {self.alt(altitude_ft, transition_altitude)}")
        else:
            parts.append("altitude unknown")
        return _join(*parts) + "."

    def traffic_no_factor(self, aircraft: Aircraft) -> str:
        return _join(aircraft.spoken(True), "previously reported traffic no factor") + "."

    # --- approach ---

    def expect_approach(self, aircraft: Aircraft, approach: str, runway: str,
                        airport: str = "") -> str:
        body = f"expect the {approach} runway {self.rwy(runway)} approach"
        if airport:
            body += f" at {airport}"
        return _join(aircraft.spoken(True), body) + "."

    def vector_to_final(
        self,
        aircraft: Aircraft,
        *,
        distance_nm: float,
        fix: str,
        heading: float,
        direction: str,
        altitude_ft: float,
        approach: str,
        runway: str,
        transition_altitude: int = 0,
        fix_spoken: str = "",
    ) -> str:
        """The standard vector-to-final clearance.

        FAA JO 7110.65 5-9-2: position relative to a fix, the intercept
        heading, the altitude to maintain until established, then the approach
        clearance. The "until established" wording is what makes it legal for
        the pilot to descend on the glideslope.
        """
        spoken_fix = fix_name(fix, fix_spoken)
        parts = [
            aircraft.spoken(True),
            f"{sp.distance(distance_nm, self.digit_dialect)} from {spoken_fix}",
            f"turn {direction} heading {self.hdg(heading)}" if direction
            else f"fly heading {self.hdg(heading)}",
            f"maintain {self.alt(altitude_ft, transition_altitude)} until established "
            f"on the localizer",
            f"cleared {approach} runway {self.rwy(runway)} approach",
        ]
        return _join(*parts) + "."

    def cleared_approach(self, aircraft: Aircraft, approach: str, runway: str,
                         *, straight_in: bool = False, maintain_ft: float = 0.0,
                         descend_ft: float = 0.0, transition_altitude: int = 0,
                         transition_level: int = 0, pressure: float = 0.0) -> str:
        """The approach clearance, with the altitude that goes with it.

        ``maintain_ft`` is the altitude to hold until established -- the
        clearance alone left the pilot guessing when the descent was theirs.
        ``descend_ft`` folds the last descent into it, for an aeroplane still
        above the intercept altitude when the clearance falls due: "descend
        to altitude 3000 ft, QNH 1018, cleared ILS approach runway 25L"
        (ICAO Doc 9432). The FAA puts the altitude before the clearance
        ("maintain three thousand until established on the localizer,
        cleared ILS runway two five left approach", JO 7110.65 4-8-1).
        """
        prefix = "cleared straight-in" if straight_in else "cleared"
        clearance = f"{prefix} {approach} runway {self.rwy(runway)} approach"
        parts = [aircraft.spoken(True)]
        if descend_ft:
            verb = "descend and maintain" if self.dialect == "faa" else "descend to"
            parts.append(f"{verb} {self.alt(descend_ft, transition_altitude, transition_level)}")
            if pressure and not sp.is_flight_level(
                    descend_ft, transition_altitude or self.transition,
                    transition_level):
                parts.append(self.pressure(pressure))
        if maintain_ft:
            held = self.alt(maintain_ft, transition_altitude, transition_level)
            if self.dialect == "faa":
                course = ("the localizer" if approach.upper() in ("ILS", "LOC")
                          else "the final approach course")
                parts += [f"maintain {held} until established on {course}",
                          clearance]
            else:
                parts += [clearance, f"maintain {held} until established"]
        else:
            parts.append(clearance)
        return _join(*parts) + "."

    def cleared_visual_approach(self, aircraft: Aircraft, runway: str,
                                airport: str = "") -> str:
        body = f"cleared visual approach runway {self.rwy(runway)}"
        if airport:
            body = f"cleared visual approach {airport} runway {self.rwy(runway)}"
        return _join(aircraft.spoken(True), body) + "."

    def report_field_in_sight(self, aircraft: Aircraft, airport: str,
                              oclock: int = 0, distance_nm: float = 0) -> str:
        words = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six",
                 7: "seven", 8: "eight", 9: "niner", 10: "ten", 11: "eleven",
                 12: "twelve"}
        parts = [aircraft.spoken(True)]
        if oclock and distance_nm:
            parts.append(
                f"{airport} airport {words.get(oclock, self.d(oclock))} o'clock, "
                f"{sp.distance(distance_nm, self.digit_dialect)}"
            )
        parts.append("report the field in sight")
        return _join(*parts) + "."

    def descend_via(self, aircraft: Aircraft, arrival: str) -> str:
        return _join(aircraft.spoken(True), f"descend via the {arrival} arrival") + "."

    def climb_via_sid(self, aircraft: Aircraft, departure: str,
                      top_altitude: float = 0.0,
                      transition_altitude: int = 0) -> str:
        body = f"climb via the {departure} departure"
        if top_altitude:
            body += f", except maintain {self.alt(top_altitude, transition_altitude)}"
        return _join(aircraft.spoken(True), body) + "."

    def holding_instruction(
        self, aircraft: Aircraft, fix: str, radial: float, direction: str,
        turns: str = "right", leg_minutes: int = 1, efc: str = "",
        altitude_ft: float = 0.0, transition_altitude: int = 0,
        fix_spoken: str = "",
    ) -> str:
        """A full holding clearance, in the order ICAO Doc 4444 prescribes."""
        spoken_fix = fix_name(fix, fix_spoken)
        parts = [
            aircraft.spoken(True),
            f"hold {direction} of {spoken_fix}",
            f"on the {self.hdg(radial)} radial",
        ]
        if altitude_ft:
            parts.append(f"maintain {self.alt(altitude_ft, transition_altitude)}")
        parts.append(f"{turns} turns")
        parts.append(f"{self.d(leg_minutes)} minute legs")
        if efc:
            parts.append(f"expect further clearance {efc}")
        return _join(*parts) + "."

    # ------------------------------------------------------------------
    # VFR: airspace, advisories and levels
    # ------------------------------------------------------------------
    #
    # A VFR flight is worked on a different set of words from an IFR one, and
    # using the IFR set is the commonest way a simulated controller gives
    # itself away. It is never "cleared to" anywhere, it is never told to
    # "climb and maintain", and the level it flies is its own business unless
    # something is above it -- so the phrases here are approvals, ceilings and
    # advisories rather than clearances.

    @property
    def vfr_squawk(self) -> str:
        """The conspicuity code, which is regional: 1200 in the US, 7000 in Europe."""
        return "1200" if self.dialect == "faa" else "7000"

    def squawk_vfr(self, aircraft: Aircraft) -> str:
        if self.dialect == "faa":
            return _join(aircraft.spoken(True), "squawk VFR") + "."
        return _join(aircraft.spoken(True),
                     f"squawk {sp.squawk(self.vfr_squawk, self.digit_dialect)}") + "."

    def maintain_vfr_clause(self, altitude_ft: float = 0.0, *,
                            at_or_below: bool = True,
                            transition_altitude: int = 0) -> str:
        """The clause on its own, for a template that carries it.

        "Radar contact, maintain VFR at or below three thousand" is one
        transmission, not two, so the words have to be available without the
        callsign in front of them.
        """
        if not altitude_ft:
            return "maintain VFR"
        limit = "at or below" if at_or_below else "at or above"
        return f"maintain VFR {limit} {self.alt(altitude_ft, transition_altitude)}"

    def maintain_vfr(self, aircraft: Aircraft, altitude_ft: float = 0.0, *,
                     at_or_below: bool = True, transition_altitude: int = 0,
                     abbreviated: bool = True) -> str:
        """``"maintain VFR at or below three thousand"``.

        The only altitude instruction a VFR flight normally gets. It is a
        ceiling or a floor, not a level to hold, because holding a level is
        what an IFR aircraft does.
        """
        return _join(aircraft.spoken(abbreviated), self.maintain_vfr_clause(
            altitude_ft, at_or_below=at_or_below,
            transition_altitude=transition_altitude)) + "."

    def vfr_altitude_discretion(self, aircraft: Aircraft) -> str:
        """What a radar controller says when a VFR pilot asks for a level."""
        return _join(aircraft.spoken(True), "maintain VFR",
                     "altitude your discretion") + "."

    def cleared_through_airspace(
        self, aircraft: Aircraft, airspace: str, *, altitude_ft: float = 0.0,
        route: str = "", report: str = "", transition_altitude: int = 0,
    ) -> str:
        """A transit of somebody's airspace, on the way past.

        FAA JO 7110.65 7-8-3 and 7-9-4: Class C and B need an explicit
        clearance through, Class D needs two-way contact and an approval. All
        three are the same shape -- through what, at what level, reporting what
        -- so one template covers them.
        """
        parts = [aircraft.spoken(True), f"cleared through the {airspace}"]
        if route:
            parts.append(route)
        if altitude_ft:
            parts.append(
                f"maintain VFR at or below {self.alt(altitude_ft, transition_altitude)}")
        else:
            parts.append("maintain VFR")
        if report:
            parts.append(f"report {report}")
        return _join(*parts) + "."

    def remain_clear_of_airspace(self, aircraft: Aircraft, airspace: str,
                                 station: str = "", *, reason: str = "") -> str:
        """The refusal, which is a real answer and has to be available.

        "Remain outside Class Charlie" is what a busy sector says, and a
        controller that can only ever approve a transit is not a controller.
        """
        parts = [self.addressed(aircraft, station),
                 f"remain clear of the {airspace}"]
        if reason:
            parts.append(reason)
        parts.append("standby")
        return _join(*parts) + "."

    def flight_following_approved(
        self, aircraft: Aircraft, station: str, squawk: str,
    ) -> str:
        """Radar advisories for a VFR flight, which start with a code.

        The code comes first, because the controller cannot identify the
        aircraft until it is squawking one; "radar contact" follows on the next
        transmission, once it can see it.
        """
        return _join(
            self.addressed(aircraft, station),
            f"squawk {sp.squawk(squawk, self.digit_dialect)}",
            "maintain VFR",
        ) + "."

    def flight_following_unavailable(self, aircraft: Aircraft) -> str:
        """Advisories are workload permitting, and sometimes the answer is no."""
        return _join(aircraft.spoken(True),
                     "unable flight following due to controller workload",
                     "remain VFR") + "."

    # ------------------------------------------------------------------
    # handoffs
    # ------------------------------------------------------------------

    def handoff(
        self, aircraft: Aircraft, next_station: str, next_freq: float,
        *, when: str = "", farewell: bool = False, welcome: str = "",
        abbreviated: bool = True,
    ) -> str:
        """Transfer of communication.

        FAA phrasing is "contact <facility> <frequency>" with no "on"; a
        good-day is common but never part of the instruction itself.

        ``welcome`` is the arrival version of that courtesy, and it names the
        place: a tower that has just watched you land says "welcome to
        Prague" rather than "have a good flight", which is what it says to
        somebody leaving.
        """
        parts = [self.addressed(aircraft, "", abbreviated)]
        if welcome:
            parts.append(f"welcome to {welcome}")
        body = f"contact {next_station} {self.freq(next_freq)}"
        if when:
            body = f"{when}, {body}"
        parts.append(body)
        text = _join(*parts) + "."
        # A welcome is the farewell for an arrival. Saying both would be
        # greeting somebody and taking leave of them in one breath.
        if farewell and not welcome:
            text += " " + _pick(
                ("Good day.", "So long.", "Have a good flight."),
                aircraft.callsign.written + next_station,
            )
        return text

    def monitor(self, aircraft: Aircraft, next_station: str, next_freq: float) -> str:
        """"Monitor" means listen without checking in."""
        return _join(aircraft.spoken(True),
                     f"monitor {next_station} {self.freq(next_freq)}") + "."

    def remain_this_frequency(self, aircraft: Aircraft) -> str:
        return _join(aircraft.spoken(True), "remain this frequency") + "."

    def frequency_change_approved(self, aircraft: Aircraft) -> str:
        return _join(aircraft.spoken(True), "frequency change approved") + "."

    def radar_service_terminated(self, aircraft: Aircraft, *,
                                 squawk_vfr: bool = True,
                                 next_station: str = "", next_freq: float = 0.0) -> str:
        parts = [aircraft.spoken(True), "radar service terminated"]
        if squawk_vfr:
            parts.append("squawk VFR")
        if next_station and next_freq:
            parts.append(f"contact {next_station} {self.freq(next_freq)}")
        else:
            parts.append("frequency change approved")
        return _join(*parts) + "."

    # ------------------------------------------------------------------
    # transponder, altimeter, general
    # ------------------------------------------------------------------

    def squawk(self, aircraft: Aircraft, code: str) -> str:
        return _join(aircraft.spoken(True),
                     f"squawk {sp.squawk(code, self.digit_dialect)}") + "."

    def ident(self, aircraft: Aircraft) -> str:
        return _join(aircraft.spoken(True), "ident") + "."

    def pressure(self, value: float) -> str:
        """Altimeter setting in the units the region uses.

        The *format* follows the region -- four digits of inches with no
        decimal point in the US, four digits of hectopascals elsewhere -- while
        the digit words follow the configured style.
        """
        if self.dialect == "faa":
            return f"altimeter {self.d(f'{float(value):.2f}'.replace('.', ''))}"
        # Three figures below a thousand: "QNH niner niner zero", never with
        # a zero in front of it.
        return f"QNH {self.d(str(int(round(float(value)))))}"

    def wind(self, weather: Weather) -> str:
        direction = spoken_wind_direction(weather)
        if (direction == "VRB" and self.dialect == "icao"
                and int(round(weather.wind_kt)) > 0):
            # ICAO reads a variable wind with its unit, "wind variable five
            # knots"; the FAA form, "wind variable at five" (JO 7110.65
            # 2-6-4), is what sp.wind already says.
            text = f"wind variable {self.d(int(round(weather.wind_kt)))} knots"
            if weather.gust_kt and weather.gust_kt > weather.wind_kt:
                text += f" gusting {self.d(int(round(weather.gust_kt)))}"
            return text
        return sp.wind(direction, weather.wind_kt,
                       weather.gust_kt or None, self.digit_dialect)

    def altimeter_setting(self, aircraft: Aircraft, value: float) -> str:
        return _join(aircraft.spoken(True), self.pressure(value)) + "."

    def say_again(self, aircraft: Aircraft | None = None, item: str = "") -> str:
        if item:
            body = f"say again your {item}"
        else:
            body = _pick(("say again", "say again, you were unreadable"),
                         item or "x")
        if aircraft:
            return _join(aircraft.spoken(True), body) + "."
        return body.capitalize() + "."

    def expecting(self, aircraft: Aircraft, calls: Sequence[str] = ()) -> str:
        """Name the call the controller is waiting for.

        "Say again" tells a pilot that they were not understood and nothing
        else, which on a frequency they have never worked before is no help at
        all. Naming the call is: the controller knows what would make sense
        here, and there is no reason to keep it to itself.
        """
        wanted = [call for call in calls if call]
        if not wanted:
            return self.say_again(aircraft)
        if len(wanted) == 1:
            body = f"expecting {wanted[0]}"
        else:
            body = "expecting " + ", or ".join(wanted)
        return _join(aircraft.spoken(True), body) + "."

    def roger(self, aircraft: Aircraft) -> str:
        return _join(aircraft.spoken(True),
                     _pick(("roger", "roger that"), aircraft.callsign.written)) + "."

    def roger_runway(self, aircraft: Aircraft, runway: str) -> str:
        """Acknowledge a runway the pilot asked for, by naming it back.

        A bare "roger" to "request runway three zero" is indistinguishable
        from not having heard it, which is the whole of what was wrong: the
        pilot asks again, gets another roger, and taxis to the other runway.
        """
        return _join(aircraft.spoken(True), "roger",
                     f"expect runway {self.rwy(runway)}") + "."

    def standby(self, aircraft: Aircraft) -> str:
        return _join(aircraft.spoken(True), "standby") + "."

    def unable(self, aircraft: Aircraft, reason: str = "") -> str:
        parts = [aircraft.spoken(True), "unable"]
        if reason:
            parts.append(reason)
        return _join(*parts) + "."

    def wilco_expected(self, aircraft: Aircraft, instruction: str) -> str:
        return _join(aircraft.spoken(True), instruction) + "."

    def verify(self, aircraft: Aircraft, item: str) -> str:
        return _join(aircraft.spoken(True), f"verify {item}") + "."

    def radio_check(self, aircraft: Aircraft, readability: int = 5) -> str:
        return _join(aircraft.spoken(True),
                     f"read you {self.d(readability)} by {self.d(readability)}") + "."

    def no_reply(self, aircraft: Aircraft, station: str) -> str:
        """Controller calling an aircraft that has not answered."""
        return _join(aircraft.spoken(False), station, "how do you hear") + "?"

    # ------------------------------------------------------------------
    # when the aircraft and the request do not agree
    # ------------------------------------------------------------------
    #
    # A controller looks out of the window, or at the radar, before answering.
    # Asking for a takeoff clearance from four thousand feet gets an answer
    # about the aircraft, not a clearance, and these are those answers.

    def already_airborne(self, aircraft: Aircraft) -> str:
        return _join(aircraft.spoken(True), "you are airborne",
                     "say intentions") + "."

    def already_on_the_ground(self, aircraft: Aircraft) -> str:
        return _join(aircraft.spoken(True), "you are on the ground",
                     "say intentions") + "."

    def already_cleared_for_takeoff(self, aircraft: Aircraft, runway: str) -> str:
        return _join(aircraft.spoken(True), "you are already cleared for takeoff",
                     f"runway {self.rwy(runway)}") + "."

    def already_cleared_to_land(self, aircraft: Aircraft, runway: str) -> str:
        return _join(aircraft.spoken(True), "you are already cleared to land",
                     f"runway {self.rwy(runway)}") + "."

    # ------------------------------------------------------------------
    # what the controller says without being asked
    # ------------------------------------------------------------------
    #
    # An aircraft that takes a runway, departs or lands without a clearance is
    # not ignored, which is what used to happen here. In US airspace the reply
    # is the "possible pilot deviation" advisory of FAA JO 7110.65 2-1-27,
    # which is a formal notice, not a telling-off; the number to call is issued
    # by telephone afterwards, so this says which facility rather than
    # inventing one.

    def hold_position_incursion(self, aircraft: Aircraft, runway: str) -> str:
        return _join(aircraft.spoken(True), "hold position",
                     f"you have entered runway {self.rwy(runway)} without a clearance") + "."

    def departed_without_clearance(self, aircraft: Aircraft, runway: str,
                                   station: str = "") -> str:
        where = f" runway {self.rwy(runway)}" if runway else ""
        parts = [aircraft.spoken(True),
                 f"you departed{where} without a takeoff clearance",
                 "possible pilot deviation"]
        if station:
            parts.append(f"advise you contact {station} after landing")
        return _join(*parts) + "."

    def landed_without_clearance(self, aircraft: Aircraft, runway: str,
                                 station: str = "") -> str:
        where = f" runway {self.rwy(runway)}" if runway else ""
        parts = [aircraft.spoken(True),
                 f"you landed{where} without a landing clearance",
                 "possible pilot deviation"]
        if station:
            parts.append(f"advise you contact {station} after you park")
        return _join(*parts) + "."

    # ------------------------------------------------------------------
    # emergencies
    # ------------------------------------------------------------------

    # ------------------------------------------------------------------
    # stock instructions
    # ------------------------------------------------------------------
    #
    # These exist so the controller logic never contains a literal English
    # sentence. Every phrase a controller can utter lives in a phraseology
    # class, which is what makes a second language a matter of writing another
    # class rather than of finding strings scattered through the decision code.

    # Fragments the decision layer needs to pass back into a template.
    ROUTE_RADAR_VECTORS = "radar vectors, then as filed"

    @property
    def ROUTE_AS_FILED(self) -> str:
        """After a SID: "then as filed" (FAA), "flight planned route"
        (ICAO Doc 9432)."""
        return "as filed" if self.dialect == "faa" else "flight planned route"
    RUNWAY_HEADING = "fly runway heading"
    PARKING = "the ramp"
    UNKNOWN_DESTINATION = "your destination"
    DEFAULT_APPROACH = "ILS"

    def approach_name(self, kind: str) -> str:
        """An approach type as it is said: "localizer", "visual", "ILS"."""
        return {"LOC": "localizer", "VISUAL": "visual"}.get(kind, kind)

    # Reporting points a tower uses to sequence a circuit. These are the whole
    # of how a non-radar tower keeps VFR aircraft apart, so they are stock
    # phrases rather than something the decision layer assembles.
    REPORT_MIDFIELD_DOWNWIND = "midfield downwind"
    REPORT_TURNING_BASE = "turning base"
    REPORT_ENTERING_DOWNWIND = "entering the downwind"

    # --- how the decision layer names things a language spells differently ---

    _LEGS = {"downwind": "downwind", "base": "base", "final": "final",
             "crosswind": "crosswind", "upwind": "upwind"}
    _SIDES = {"left": "left", "right": "right"}
    _AIRSPACE_FAA = {"B": "Class Bravo", "C": "Class Charlie",
                     "D": "Class Delta"}
    _AIRSPACE_ICAO = {"B": "terminal control area", "C": "terminal area",
                      "D": "control zone"}

    def leg(self, name: str) -> str:
        """A circuit leg, named the way this language names it."""
        return self._LEGS.get((name or "").lower(), self._LEGS["downwind"])

    def side(self, name: str) -> str:
        """"left" or "right", for a circuit direction or a turn."""
        return self._SIDES.get((name or "").lower(), self._SIDES["left"])

    _BEARINGS = {
        "north": "north", "northeast": "northeast", "east": "east",
        "southeast": "southeast", "south": "south", "southwest": "southwest",
        "west": "west", "northwest": "northwest",
    }

    def bearing(self, name: str) -> str:
        """A compass direction, as this language says it.

        The decision layer works in English names because that is what the
        parser hands it; what reaches the radio is the local word, or nothing
        when the language has no entry for it.
        """
        return self._BEARINGS.get((name or "").lower(), "")

    def airspace(self, kind: str = "D") -> str:
        """What the airspace round a facility is called here.

        The US names airspace by class on the radio; ICAO states name the
        volume -- "the control zone", "the TMA" -- and a pilot in Europe is not
        asked to transit a Class Delta.
        """
        table = self._AIRSPACE_FAA if self.dialect == "faa" else self._AIRSPACE_ICAO
        return table.get((kind or "D").upper(), table["D"])

    def clear_of(self, airspace: str) -> str:
        """A reporting point: ``"clear of the Class Delta"``."""
        return f"clear of the {airspace}"

    def miles_final(self, nm: float) -> str:
        """A reporting point: ``"a two mile final"``.

        The distance is singular here -- "a two mile final", not "two miles" --
        because it is an adjective on the leg rather than a distance in its own
        right, which is why it is not ``sp.distance``.
        """
        return f"a {self.d(int(round(nm)))} mile final"

    def pushback_approved(self, aircraft: Aircraft) -> str:
        return _join(aircraft.spoken(True), "push and start approved",
                     "advise ready to taxi") + "."

    def maintain_visual_separation(self, aircraft: Aircraft) -> str:
        return _join(aircraft.spoken(True), "maintain visual separation",
                     "follow that traffic") + "."

    def ifr_cancelled(self, aircraft: Aircraft) -> str:
        return _join(aircraft.spoken(True), "IFR cancellation received",
                     "squawk VFR", "frequency change approved") + "."

    def unable_lower(self, aircraft: Aircraft) -> str:
        return self.unable(aircraft, "maintain your present altitude")

    def unable_unknown_fix(self, aircraft: Aircraft) -> str:
        return self.unable(aircraft, "say again the fix")

    def unable_unknown_destination(self, aircraft: Aircraft) -> str:
        return self.unable(aircraft, "say your destination")

    def go_around_standard(self, aircraft: Aircraft, altitude_ft: float = 3000,
                           transition_altitude: int = 0) -> str:
        verb = "climb and maintain" if self.dialect == "faa" else "climb to"
        return self.go_around(
            aircraft, "",
            f"{self.RUNWAY_HEADING}, {verb} {self.alt(altitude_ft, transition_altitude)}",
        )

    def correction(
        self,
        aircraft: Aircraft,
        wrong: list[str],
        values: dict,
        current_altitude_ft: float = 0.0,
        transition_altitude: int = 0,
    ) -> str:
        """Correct the items a pilot read back wrongly, and only those."""
        parts: list[str] = []
        for key in wrong:
            value = values[key]
            if key == "altitude_ft":
                # Re-issue with the verb matching the direction the aircraft
                # has to go; correcting a descent with the word "climb" is the
                # exact confusion a readback exists to prevent.
                descending = current_altitude_ft and float(value) < current_altitude_ft
                if self.dialect == "faa":
                    verb = "descend and maintain" if descending else "climb and maintain"
                else:
                    verb = "descend to" if descending else "climb to"
                parts.append(f"{verb} {self.alt(value, transition_altitude)}")
            elif key == "heading":
                parts.append(f"fly heading {self.hdg(value)}")
            elif key == "runway":
                parts.append(f"runway {self.rwy(value)}")
            elif key == "squawk":
                parts.append(f"squawk {self.d(value)}")
            elif key == "frequency":
                parts.append(f"contact on {self.freq(value)}")
            elif key == "speed_kt":
                parts.append(f"speed {self.d(int(value))} knots")
            elif key == "hold_short":
                # Name the runway. "Hold short, read back" told a pilot who had
                # just read back the wrong runway nothing about which one.
                if isinstance(value, str) and value:
                    parts.append(f"hold short of runway {self.rwy(value)}")
                else:
                    parts.append("hold short")
        return self.readback_incorrect(aircraft, ", ".join(parts) + ", read back")

    def emergency_acknowledged(
        self, aircraft: Aircraft, station: str, *, runway: str = "",
        souls_and_fuel: bool = True,
    ) -> str:
        parts = [self.addressed(aircraft, station), "roger",
                 "state the nature of your emergency"]
        if souls_and_fuel:
            parts.append("souls on board and fuel remaining")
        return _join(*parts) + "."

    def emergency_priority(self, aircraft: Aircraft, runway: str,
                           heading: float = 0.0, equipment: bool = True) -> str:
        """Priority and a runway.

        ``equipment`` turns the fire service out, which is right for a
        declared emergency and wrong for a minimum-fuel advisory: that is a
        flight that cannot take any more delay, not one that is in trouble.
        """
        parts = [aircraft.spoken(True), "roger", "you have priority"]
        if heading:
            parts.append(f"fly heading {self.hdg(heading)}")
        parts.append(f"expect runway {self.rwy(runway)}")
        if equipment:
            parts.append("equipment is standing by")
        return _join(*parts) + "."

    def emergency_cleared_to_land(self, aircraft: Aircraft, runway: str,
                                  weather: Weather | None = None) -> str:
        parts = [aircraft.spoken(True)]
        if weather is not None:
            parts.append(self.wind(weather))
        parts += [f"runway {self.rwy(runway)}", "cleared to land",
                  "the airport is yours"]
        return _join(*parts) + "."


__all__ = ["Phraseology", "Aircraft", "Weather", "wake_suffix", "fix_name",
           "HEAVY_TYPES", "SUPER_TYPES"]
